import type { CategoryRow, TransactionRow } from "./transacciones.types";

/** Categorías mock — enlazadas por id en transacciones */
export const MOCK_CATEGORIES: CategoryRow[] = [
  { id: "cat-salary", name: "Salario", tone: "emerald" },
  { id: "cat-food", name: "Alimentación", tone: "amber" },
  { id: "cat-transport", name: "Transporte", tone: "sky" },
  { id: "cat-home", name: "Hogar", tone: "violet" },
  { id: "cat-leisure", name: "Ocio", tone: "rose" },
  { id: "cat-health", name: "Salud", tone: "emerald" },
  { id: "cat-transfer", name: "Transferencia", tone: "slate" },
  { id: "cat-services", name: "Servicios", tone: "slate" },
];

/** Cuentas mock para selects y etiquetas */
export const MOCK_ACCOUNTS = [
  { id: "acc-main", name: "Bancolombia Ahorros", currency: "COP" as const },
  { id: "acc-nomina", name: "Nequi Principal", currency: "COP" as const },
  { id: "acc-usd", name: "Wise USD", currency: "USD" as const },
  { id: "acc-pocket", name: "Bolsa vacaciones", currency: "COP" as const },
] as const;

/** Movimientos iniciales — orden cronológico descendente al mostrar */
export const MOCK_TRANSACTIONS: TransactionRow[] = [
  {
    id: "tx-001",
    at: "2026-05-03T09:15:00",
    type: "EXPENSE",
    description: "Mercado Carulla",
    amount: -189_400,
    currency: "COP",
    categoryId: "cat-food",
    accountName: "Bancolombia Ahorros",
  },
  {
    id: "tx-002",
    at: "2026-05-02T18:40:00",
    type: "EXPENSE",
    description: "Uber aeropuerto",
    amount: -42_000,
    currency: "COP",
    categoryId: "cat-transport",
    accountName: "Nequi Principal",
  },
  {
    id: "tx-003",
    at: "2026-05-02T12:00:00",
    type: "INCOME",
    description: "Nómina abril — acierto S.A.S.",
    amount: 4_850_000,
    currency: "COP",
    categoryId: "cat-salary",
    accountName: "Bancolombia Ahorros",
  },
  {
    id: "tx-004",
    at: "2026-05-01T20:05:00",
    type: "EXPENSE",
    description: "Netflix + Spotify",
    amount: -54_900,
    currency: "COP",
    categoryId: "cat-leisure",
    accountName: "Nequi Principal",
  },
  {
    id: "tx-005",
    at: "2026-05-01T08:30:00",
    type: "TRANSFER",
    description: "A ahorro vacaciones",
    amount: -600_000,
    currency: "COP",
    categoryId: "cat-transfer",
    accountName: "Bancolombia Ahorros",
    toAccountName: "Bolsa vacaciones",
  },
  {
    id: "tx-006",
    at: "2026-04-30T16:22:00",
    type: "EXPENSE",
    description: "EPS copago",
    amount: -125_000,
    currency: "COP",
    categoryId: "cat-health",
    accountName: "Bancolombia Ahorros",
  },
  {
    id: "tx-007",
    at: "2026-04-29T11:00:00",
    type: "INCOME",
    description: "Freelance diseño UI",
    amount: 890,
    currency: "USD",
    categoryId: "cat-salary",
    accountName: "Wise USD",
  },
  {
    id: "tx-008",
    at: "2026-04-28T09:00:00",
    type: "EXPENSE",
    description: "Arriendo mayo",
    amount: -1_350_000,
    currency: "COP",
    categoryId: "cat-home",
    accountName: "Bancolombia Ahorros",
  },
  {
    id: "tx-009",
    at: "2026-04-27T13:45:00",
    type: "EXPENSE",
    description: "Almuerzo equipo",
    amount: -38_500,
    currency: "COP",
    categoryId: "cat-food",
    accountName: "Nequi Principal",
  },
  {
    id: "tx-010",
    at: "2026-04-26T10:10:00",
    type: "TRANSFER",
    description: "Nequi → Bancolombia",
    amount: -500_000,
    currency: "COP",
    categoryId: "cat-transfer",
    accountName: "Nequi Principal",
    toAccountName: "Bancolombia Ahorros",
  },
  {
    id: "tx-011",
    at: "2026-04-25T07:55:00",
    type: "EXPENSE",
    description: "Energía + acueducto",
    amount: -312_400,
    currency: "COP",
    categoryId: "cat-services",
    accountName: "Bancolombia Ahorros",
  },
  {
    id: "tx-012",
    at: "2026-04-24T19:30:00",
    type: "EXPENSE",
    description: "Cine + snacks",
    amount: -48_000,
    currency: "COP",
    categoryId: "cat-leisure",
    accountName: "Nequi Principal",
  },
  {
    id: "tx-013",
    at: "2026-04-23T14:00:00",
    type: "INCOME",
    description: "Reembolso seguro",
    amount: 210_000,
    currency: "COP",
    categoryId: "cat-health",
    accountName: "Bancolombia Ahorros",
  },
  {
    id: "tx-014",
    at: "2026-04-10T12:00:00",
    type: "EXPENSE",
    description: "Gimnasio anual (prorrateo)",
    amount: -95_000,
    currency: "COP",
    categoryId: "cat-health",
    accountName: "Nequi Principal",
  },
  {
    id: "tx-015",
    at: "2026-03-28T09:00:00",
    type: "INCOME",
    description: "Bono trimestral",
    amount: 1_200_000,
    currency: "COP",
    categoryId: "cat-salary",
    accountName: "Bancolombia Ahorros",
  },
];
